apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlnp-ops-fe
  labels:
    app: dlnp-ops-fe
    version: 1.0.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlnp-ops-fe
  template:
    metadata:
      labels:
        app: dlnp-ops-fe
        version: 1.0.4
    spec:
      containers:
      - name: dlnp-ops-fe
        image: nstarx.azurecr.io/dlnp-ops-fe:1.0.4
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
