apiVersion: v1
kind: Service
metadata:
  name: dlnp-ops-fe
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: nstarx-ops-fe
spec:
  type: LoadBalancer
  selector:
    app: dlnp-ops-fe
  ports:
  - port: 80
    targetPort: 8080

