apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeconfigs.nstarx.com
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
spec:
  group: nstarx.com
  names:
    plural: kubeconfigs
    singular: kubeconfig
    kind: Kubeconfig
    shortNames:
      - kc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kubeconfig:
                  type: string
                  description: "The KUBECONFIG file contents."
                cloud:
                  type: string
                  description: "The cloud provider name (e.g., aws, azure, gcp)."
              required:
                - kubeconfig
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of the resource processing."
                message:
                  type: string
                  description: "Detailed message about the current status."
                lastProcessedTime:
                  type: string
                  format: date-time
                  description: "The last time this resource was processed."
      additionalPrinterColumns:
        - name: Cloud
          type: string
          jsonPath: .spec.cloud
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}