image:
  repository: nstarx.azurecr.io/dlnp-ops-fe
  tag: 1.0.4
  pullPolicy: IfNotPresent

# Additional configuration
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources: {}

service:
  type: ClusterIP
  port: 80
