flDemoUi:
  flDemoUi:
    image:
      repository: nstarx.azurecr.io/sumit-fl-demo/fl-demo-ui
      tag: latest
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
