{{- if not .Values.operator.watch.clusterWide }}
# This role allows the operator to install and manage CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dlnp-operator.fullname" . }}-crd
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
rules:
  # For creating and managing CRDs
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dlnp-operator.fullname" . }}-crd
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dlnp-operator.fullname" . }}-crd
subjects:
  - kind: ServiceAccount
    name: {{ include "dlnp-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}