{{- if .Values.operator.watch.clusterWide }}
# Cluster-wide permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dlnp-operator.fullname" . }}
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering)
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  
  # Framework: posting the events about the handlers progress/errors
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  
  # Application: watching & handling for kubeconfig resources and updating their statuses
  - apiGroups: [nstarx.com]
    resources: [kubeconfigs, kubeconfigs/status]
    verbs: [get, list, watch, patch, update]
    
  # For creating and managing CRDs
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
    
  # For reading/creating secrets to store kubeconfigs
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
    
  # For reading/creating temporary pods if needed
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, update, patch, delete]
    
  # For listing namespaces
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
{{- else }}
# Namespace-scoped permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dlnp-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering)
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  
  # Framework: posting the events about the handlers progress/errors
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
    
  # For reading/creating secrets to store kubeconfigs
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
    
  # For reading/creating temporary pods if needed
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, update, patch, delete]

  # Application: watching & handling for kubeconfig resources and updating their statuses
  - apiGroups: [nstarx.com]
    resources: [kubeconfigs, kubeconfigs/status]
    verbs: [get, list, watch, patch, update]
{{- end }}