{{- if .Values.operator.watch.clusterWide }}
# Cluster-wide role binding for cluster-wide mode
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dlnp-operator.fullname" . }}
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dlnp-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dlnp-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
# Namespace-scoped role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dlnp-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dlnp-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dlnp-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dlnp-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}