apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-cm.fullname" . }}-default-config
  labels:
  {{- include "my-cm.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.defaultConfig.appEnv | quote }}
  LOG_LEVEL: {{ .Values.defaultConfig.logLevel | quote }}
  TIMEOUT_SECONDS: {{ .Values.defaultConfig.timeoutSeconds | quote }}